src/main/java/com/daw/cinuja/DAO/models/Pelicula.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.daw.cinuja.DAO.models;

import java.util.Date;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 *
 *
 * @author lopez
 */
public class Pelicula {

    @NotNull(message = "Todas las peliculas necesitan tener un titulo")
    @Size(min = 2, max = 30, message = "El titulo de una pelicula debe de tener entre {min} y {max} caracteres")
    private String titulo;
    @NotNull(message = "Se necesita que la pelicuta tenga la url con la que se mostrara en el navegador")
    @Pattern(regexp = "^[a-z]+(-[a-z]+)*", message = "La url no tiene el formato correcto (todo debe tener minusculas y separado por -)")
    private String url;
    //tambien puede ser una pelicula no estrenada
    //@Past(message = "La fecha en la que se estrenó la pelicula tiene que ser anterior a la actual")
    private Date fecha;//estreno
    @Pattern(regexp = "^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]", message = "La foto debe ser de una url")
    private String foto;//url 
    @Min(value = 0, message = "La suma de los votos no puede ser menor que 0")
    private long sumaVotos;
    @Min(value = 0, message = "El numero de votos no puede ser menor que {value}")
    private long nVotos;
    @Min(value = 0, message = "El genero debe de ser un indice de la lista de generos")
    //@Max(value = PeliculaDAO.generos.size())
    private int genero;//indice
    @Size(min = 3, max = 256, message = "El tamaño de la descripción debe de estar entre {min} y {max}")
    private String descripcion;
    private boolean restriccionEdad;//restricción de edad
    @Valid
    private Director director;

    public Pelicula() {
        this.titulo = "";
        this.url = "";
        this.fecha = new Date();
        this.foto = "";
        this.sumaVotos = 0;
        this.nVotos = 0;
        this.genero = 0;
        this.descripcion = "";
        this.restriccionEdad = false;
        this.director = new Director();
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.titulo);
        hash = 37 * hash + Objects.hashCode(this.fecha);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Pelicula other = (Pelicula) obj;
        if (!Objects.equals(this.titulo, other.titulo)) {
            return false;
        }
        return Objects.equals(this.fecha, other.fecha);
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public float getNota() {
        if (this.getnVotos() <= 0) {
            return 0;
        } else {
            return ((float) this.getSumaVotos()) / ((float) this.getnVotos());
        }
    }

    public int getGenero() {
        return genero;
    }

    public void setGenero(int genero) {
        this.genero = genero;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public boolean isRestriccionEdad() {
        return restriccionEdad;
    }

    public void setRestriccionEdad(boolean restriccionEdad) {
        this.restriccionEdad = restriccionEdad;
    }

    public Director getDirector() {
        return director;
    }

    public void setDirector(Director director) {
        this.director = director;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public long getSumaVotos() {
        return sumaVotos;
    }

    public void setSumaVotos(long sumaVotos) {
        this.sumaVotos = sumaVotos;
    }

    public long getnVotos() {
        return nVotos;
    }

    public void setnVotos(long nVotos) {
        this.nVotos = nVotos;
    }

}

src/main/java/com/daw/cinuja/controller/PeliculaController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.daw.cinuja.controller;

import com.daw.cinuja.DAO.interfaces.ComentarioDAO;
import com.daw.cinuja.DAO.interfaces.DAOConfig;
import com.daw.cinuja.DAO.interfaces.PeliculaDAO;
import com.daw.cinuja.DAO.models.Comentario;
import com.daw.cinuja.DAO.models.Pelicula;
import com.daw.cinuja.DAO.models.Sesion;
import com.daw.cinuja.DTO.ComentarioDTO;
import com.daw.cinuja.DTO.PeliculaDTO;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author lopez
 */
@Controller
@RequestMapping("/pelicula")
public class PeliculaController {

    @Autowired
    @Qualifier(DAOConfig.peliculaQualifier)
    private PeliculaDAO peliculas;

    @Autowired
    @Qualifier(DAOConfig.comentarioQualifier)
    private ComentarioDAO comentarios;

    @Autowired
    private Sesion sesion;

    public PeliculaController() {
    }

    @ModelAttribute("sesion")
    public Sesion getSesion() {
        return sesion;
    }

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @ModelAttribute
    protected void processRequest(@PathVariable(required = false) String url_peli, HttpServletRequest request, HttpServletResponse response, ModelMap model)
            throws ServletException, IOException {
        response.setContentType("text/html; charset=UTF-8");
//        request.setCharacterEncoding("UTF-8");
    }

    @GetMapping("/{url_peli}")
    public String visualiza(ModelMap model, @PathVariable String url_peli) {
        if (sesion.getUsuario() != null) {
            model.addAttribute("comentarioDTO", new ComentarioDTO());
        }

        Pelicula p = peliculas.getPelicula(url_peli);
        model.addAttribute("pelicula", p);
        model.addAttribute("comentarios", comentarios.getComentarios(p));

        return "pelicula";
    }

    @GetMapping("/{url_peli}/borrar")
    public String borra(@PathVariable String url_peli) {
        peliculas.borrar(peliculas.getPelicula(url_peli));
        return "redirect:/portada";
    }

    @PostMapping(value = "/{url_peli}", params = "estrellas")
    public String estrellas(@PathVariable String url_peli, @RequestParam(value = "estrellas", defaultValue = "0", required = true) int estrellas) {
        Pelicula p = peliculas.getPelicula(url_peli);
        p.setSumaVotos(p.getSumaVotos() + estrellas);
        p.setnVotos(p.getnVotos() + 1);
        peliculas.modificar(p, p);
        return "redirect:/pelicula/" + url_peli;
    }

    @PostMapping(value = "/{url_peli}")
    public String comentario(ModelMap model, @PathVariable String url_peli, @ModelAttribute("comentarioDTO") @Valid ComentarioDTO cDTO, BindingResult errores) {
        String url = "pelicula";

        if (!errores.hasErrors()) {
            url = "redirect:/" + url + "/" + url_peli;
            Comentario c = new Comentario();
            c.setPelicula(peliculas.getPelicula(url_peli));
            c.setUsuario(sesion.getUsuario());
            c.setTitulo(cDTO.getTitulo());
            c.setTexto(cDTO.getTexto());
            c.setFecha(new Date());
            comentarios.insertar(c);
            model.clear();
        }

        //si hay errores no hacer redirect
        return url;
    }

    @PostMapping("/crear")
    public String crear(ModelMap model, @ModelAttribute("peliculaDTO") @Valid PeliculaDTO pDTO, BindingResult errores) {
        String url = "redirect:/portada";

        if (!errores.hasErrors()) {
            try {
                url = "redirect:/pelicula/" + pDTO.getUrl();

                Pelicula p = new Pelicula();
                p.setTitulo(pDTO.getTitulo());
                p.setUrl(pDTO.getUrl());
                p.setFecha(new SimpleDateFormat("yyyy-MM-dd").parse(pDTO.getFecha()));
                p.setFoto(pDTO.getFoto());
                p.setGenero(pDTO.getGenero());
                peliculas.insertar(p);
            } catch (ParseException ex) {
                Logger.getLogger(PeliculaController.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return url;
    }
}

src/main/java/com/daw/cinuja/controller/UsuarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.daw.cinuja.controller;

import com.daw.cinuja.DAO.interfaces.ComentarioDAO;
import com.daw.cinuja.DAO.interfaces.DAOConfig;
import com.daw.cinuja.DAO.interfaces.PeliculaDAO;
import com.daw.cinuja.DAO.interfaces.UsuarioDAO;
import com.daw.cinuja.DAO.models.Comentario;
import com.daw.cinuja.DAO.models.Sesion;
import com.daw.cinuja.DAO.models.Usuario;
import com.daw.cinuja.DTO.ComentarioDTO;
import com.daw.cinuja.DTO.UsuarioDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 *
 * @author lopez
 */
@Controller
@RequestMapping("/perfil")
public class UsuarioController {

    @Autowired
    @Qualifier(DAOConfig.usuarioQualifier)
    private UsuarioDAO usuarios;

    @Autowired
    @Qualifier(DAOConfig.comentarioQualifier)
    private ComentarioDAO comentarios;

    @Autowired
    private Sesion sesion;

    @ModelAttribute("comentario")
    public ComentarioDTO getComentario() {
        return new ComentarioDTO();
    }

    @ModelAttribute("sesion")
    public Sesion getSesion() {
        return sesion;
    }

    @ModelAttribute
    protected void processRequest(ModelMap model, HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html; charset=UTF-8");
        request.setCharacterEncoding("UTF-8");
        model.addAttribute("usuarioDTO", new UsuarioDTO());
    }

    @GetMapping("")
    public String visualiza(ModelMap model, HttpServletRequest request) {
        sesion.setUsuario(usuarios.getUsuario(request.getRemoteUser()));
        model.addAttribute("comentarios", comentarios.getComentarios(sesion.getUsuario()));
        model.addAttribute("generos", PeliculaDAO.generos);
        model.addAttribute("perfil", sesion.getUsuario());

        return "usuario";
    }

    @GetMapping("/salir")
    public String salir(HttpSession session) {
        sesion.setUsuario(null);
        session.invalidate();
        return "redirect:/portada";
    }

    @GetMapping("/cc")
    public String visuzalizaCambiaContrasena() {
        return "contrasena";
    }

    @PostMapping("/cc")
    public String cambiaContrasena(@RequestParam(value = "contrase", required = true) String contra) {
        Usuario u = sesion.getUsuario();
        u.setContrasena(contra);
        usuarios.modificar(sesion.getUsuario(), u);
        return "redirect:salir";
    }

    @GetMapping("/borrar/comentario")
    public String borrarComentario(@RequestParam(value = "id", defaultValue = "0") Integer id, ModelMap model) {
        comentarios.borrar(comentarios.getComentarios(sesion.getUsuario()).get(id));
        return "redirect:/perfil";
    }

    @PostMapping("/modifica/comentario")
    public String modificarComentario(
            @ModelAttribute("comentario") @Valid ComentarioDTO cDTO, BindingResult errores,
            @RequestParam(value = "id", defaultValue = "0") Integer id, ModelMap model) {
        String url = "usuario";

        Comentario c = comentarios.getComentarios(sesion.getUsuario()).get(id);
        ComentarioDTO CDTO = new ComentarioDTO();
        CDTO.setTitulo(c.getTitulo());
        CDTO.setTexto(c.getTexto());

        if (cDTO.equals(CDTO)) {
            errores.rejectValue("titulo", "error.comentario.titulo", "No se ha modificado el titulo");
            errores.rejectValue("texto", "error.comentario.texto", "No se ha modificado el texto");
        }

        if (!errores.hasErrors()) {
            url = "redirect:/perfil";
            c.setTitulo(cDTO.getTitulo());
            c.setTexto(cDTO.getTexto());
            comentarios.modificar(c, c);
        } else {
            model.addAttribute("comentarios", comentarios.getComentarios(sesion.getUsuario()));
            model.addAttribute("generos", PeliculaDAO.generos);
            model.addAttribute("perfil", sesion.getUsuario());
        }

        return url;
    }

    @GetMapping("/registro")
    public String registro() {
        return "registro";
    }

    @PostMapping(value = "/registro")
    public String comentario(ModelMap model,
            @ModelAttribute("usuarioDTO") @Valid UsuarioDTO uDTO, BindingResult errores,
            @RequestParam(value = "contrasena2", defaultValue = "") String contrasena
    ) {
        String url = "registro";

        if (!uDTO.isTerminos()) {
            errores.rejectValue("terminos", "error.cliente.terminos", "Debes de aceptar los terminos de usuario");
        }

        if (!uDTO.getContrasena().equals(contrasena) || contrasena.isEmpty()) {
            errores.addError(new FieldError("contrasena2", "contrasena2", "Las contraseñas no son iguales"));
        } else {
            model.addAttribute("contrasena2", contrasena);
        }

        if (usuarios.getUsuario(uDTO.getNick()) != null) {
            errores.rejectValue("nick", "error.cliente.nick", "Ya hay otro usuario con ese nick");
        }

        if (!errores.hasErrors()) {
            url = "redirect:/perfil";
            Usuario u = new Usuario();
            u.setNick(uDTO.getNick());
            u.setNombre(uDTO.getNombre());
            u.setApellidos(uDTO.getApellidos());
            u.setContrasena(uDTO.getContrasena());
            u.setFoto("http://scapp.ie20deenero.edu.co/assets/img/defaultcon.png");
            usuarios.insertar(u);
            model.clear();
        } else {
            List<Object> errs = new ArrayList<>();

            for (FieldError e : errores.getFieldErrors()) {
                final String name = e.getField();
                final String msg = e.getDefaultMessage();
                String m = "{\"name\":\"" + name + "\",\"msg\":\"" + msg + "\"}";
                errs.add(m);
            }
            model.addAttribute("errors", errs);
        }

        //si hay errores no hacer redirect
        return url;
    }

}

src/main/webapp/WEB-INF/jsp/contrasena.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html" charset=UTF-8">
        <%@include file="/WEB-INF/jspf/links.jspf" %>
        <style>

            body{
                background-size: 100%;
                background-color: #f96805;
            }

        </style>

    </head>

    <body class="bg-secondary">
        <%@include file="/WEB-INF/jspf/cabecera.jspf" %>
        <div style="height: 700px; ">
            <div class="bg-white m-auto mh-700" style="height: 700px">
                <form method="POST">
                    <div class="form-row">
                    </div>

                    <div class="form-row ">
                        <div class="col-md-3 mb-3 ml-auto">
                            <p class="text-md-center" >Contraseña</p>
                            <input type="text" class="form-control" placeholder="Contraseña" required name="contrase">
                        </div>

                        <div class="col-md-3 mb-3 mr-auto">
                            <p class="text-md-center">Repetir Contraseña</p>
                            <input type="text" class="form-control" id="validationServer05" placeholder="Contraseña" required >
                        </div>

                    </div>

                    <div class="text-center">
                        <input  class="btn btn-primary" type="submit" value="Aceptar">
                        <a  class="btn btn-danger" role="button" href="${pageContext.request.contextPath}/perfil">Volver</a>
                    </div>

                    <c:forEach items="${errores}" var="error">
                        <div class="alert alert-danger">
                            ${error.message}
                        </div>
                    </c:forEach>

                </form>
            </div>
        </div>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<%-- 
    Document   : Login
    Created on : 12-mar-2019, 20:54:14
    Author     : axpos
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <%@include file="/WEB-INF/jspf/links.jspf" %>
        <meta http-equiv="Content-Type" content="text/html" charset=UTF-8">
        <style type="text/css">
            .wrapper {
                margin: 80px;
            }
            .form-signin {
                max-width: 380px;
                margin: 0 auto;
                background-color: #fff;
                padding: 15px 40px 50px;
                border: 1px solid #e5e5e5;
                border-radius: 10px;
            }
            .form-signin .form-signin-heading, .form-signin .checkbox {
                margin-bottom: 30px;
            }
            .form-signin input[type="text"], .form-signin input[type="password"] {
                margin-bottom: 20px;
            }
            .form-signin .form-control {
                padding: 10px;
            }

            #cuadro{

                position:relative;
                top: 60px;
            }
        </style>
    </head>

    <body background="https://s2.best-wallpaper.net/wallpaper/1920x1200/1711/Warm-light-circles-glare_1920x1200.jpg">

        <div id="cuadro" class="wrapper">
            <form class="form-signin" action="j_security_check" method="post">               

                <h1 class="form-signin-heading text-center"><b>🍿 CinUJA 🍿</b></h1>
                <input type="text" class="form-control" name="j_username" placeholder="Nick"  autofocus="" />
                <input type="password" class="form-control" name="j_password" placeholder="Contraseña"  />
                <c:if test="${param.error}">
                    <div class="invalid-feedback">Los campos son erroneos</div>
                </c:if>
                <input type="submit" class="btn btn-lg btn-primary btn-block" value="Entrar"/>
                <a class="btn btn-lg btn-primary btn-block" role="button" href="${pageContext.request.contextPath}/perfil/registro" >Registrarse</a>
                <a class="btn btn-danger btn-block my-2 py-2 " role="button" aria-pressed="true" href="portada" ><h5>Cancelar</h5></a>
            </form>
        </div>
    </body>
</html>

src/main/webapp/WEB-INF/jsp/pelicula.jsp
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@page contentType="text/html charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <%@include file="/WEB-INF/jspf/links.jspf" %>
        <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
        <script src="${pageContext.request.contextPath}/js/validacion/comentario.js"></script>
        <style>


            #form {
                width: 250px;
                margin: 0 auto;
                height: 50px;

            }

            #form p {
                text-align: center;

            }

            #form label {

                font-size: 30px;
                font-size: 2rem;
            }

            input[type="radio"] {
                display: none;

            }

            label {
                color: grey;
                font-size: 32px;
                font-size: 2rem;
            }

            .clasificacion {
                direction: rtl;
                unicode-bidi: bidi-override;

            }

            label:hover,
            label:hover ~ label {

                color: orange;
            }

            input[type="radio"]:checked ~ label {

                color: orange;
            }

            #boton2 {

                position:relative;
                right: 1px;
                top: 1px;
                width: 100px;
                height: 40px;
            }

            #carta {

                position:relative;
                top: -30px;
                left: 300px;

            }

        </style>

    </head>

    <body>
        <header class="cabecera">
            <%@include file="/WEB-INF/jspf/cabecera.jspf" %>
        </header>

        <main class="my-md-3 container justify-content-center" >

            <div class="card mb-3" style="max-width: 1000px; max-height: 1200px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="${pelicula.foto}" class="card-img" style="max-height: 556px; min-height: 560px;" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h2 class="card-title">${pelicula.titulo}</h2>
                            <p class="card-text">${not empty pelicula.descripcion ? pelicula.descripcion += ', en esta' : ''} película de ${pelicula.director.nombre}.</p>

                            <div><h2 style="display: inline"><b><fmt:formatNumber type="number" maxFractionDigits="1" value="${pelicula.nota}"/></b></h2><h5 style="color: gray; display: inline">/5</h5 > de ${pelicula.nVotos} votos</div>
                                        <c:if test="${not empty sesion.usuario}"> 

                                <form action="${pelicula.url}" id="frmStar" method="POST">
                                    <p class="clasificacion">

                                        <input id="radio1" type="radio" name="estrellas" value="5"><!--
                                        --><label for="radio1">★</label><!--
                                        --><input id="radio2" type="radio" name="estrellas" value="4"><!--
                                        --><label for="radio2">★</label><!--
                                        --><input id="radio3" type="radio" name="estrellas" value="3"><!--
                                        --><label for="radio3">★</label><!--
                                        --><input id="radio4" type="radio" name="estrellas" value="2"><!--
                                        --><label for="radio4">★</label><!--
                                        --><input id="radio5" type="radio" name="estrellas" value="1" checked><!--
                                        --><label for="radio5">★</label>
                                    </p>
                                    <button id="btnStar" type="submit" class="btn btn-primary" form-control value="estrellas">Valorar</button>
                                </form>
                            </c:if>

                            <div id="carta" class="card" style="width: 12rem;">
                                <c:if test="${not empty pelicula.director.foto}">
                                    <img src="${pelicula.director.foto}" class="card-img-top" style="max-height: 190px; min-height: 190px;" alt="...">
                                </c:if>
                                <div class="card-body">
                                    <p class="card-text">${pelicula.director.nombre}</p>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div> 

            <c:if test="${sesion.usuario.rol eq 'adm'}">
                <a role="button" class="btn btn-danger" href="${pelicula.url}/borrar">Borrar</a>
            </c:if>

        </main>

        <ul class="list-unstyled" >

            <c:if test="${empty comentarios}">
                <p> No hay comentarios deja el tuyo </p>
            </c:if>

            <c:forEach items="${comentarios}" var="comentario">
                <li class="media my-4">
                    <img src="${comentario.usuario.foto}" class="mr-4" alt="...">
                    <div class="media-body">
                        <h3 class="mt-0 mb-1"> ${fn:escapeXml(comentario.titulo)} </h3>
                        ${fn:escapeXml(comentario.texto)}
                        <button type="button" class="btn btn-light">👍</button>
                    </div>
                </li>
            </c:forEach>
        </ul>

        <aside class="my-md-4 container input-group justify-content-center">        
            <c:if test="${empty sesion.usuario}">
                <div class="alert alert-danger ">Inicia sesión para comentar</div>
            </c:if>

            <c:if test="${not empty sesion.usuario}">    
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Comentario no válido</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form:errors path="comentarioDTO.*" cssClass="alert alert-danger" element="div"/>
                                <div id="errores"></div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            </div>
                        </div>
                    </div>
                </div>

                <form:form id="frmcmt" method="POST" modelAttribute="comentarioDTO">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon3">Titulo</span>
                        </div>
                        <form:input path="titulo" cssClass="form-control" id="tittle"/>
                    </div>
                    <form:textarea path="texto" cssClass="input-group-text form-control text-left" id="texto" rows="10" cols="120" placeholder="Escribe aquí tu comentario"/>
                    <input class="btn btn-primary form-control" type="submit" data-toggle="modal" data-target="#exampleModal" value="Comentar" >
                </form:form>
            </c:if>
        </aside>

    </body>
</html>